### ISSUE TITLE
API Version Mismatch

### ISSUE THREAD

**Issue by 15bitgames** [TobiasTheViking/sabcli#1]
I'm currently using Sabnzbd 0.7.14 with Sabcurses 0.7.11 and I noticed an API mismatch.  If I go into the "MORE" section I get.

WARNING: API version mismatch between SABCurses (0.7.11) and daemon (0.7.14)

Is there an easy way to resolve this issue?

**Comment by TobiasTheViking** [comment]
It really doesn't matter at all. just ignore it.

**Comment by 15bitgames** [comment]
Cheers for that Tobias.
