### ISSUE TITLE
Large History Crashed sabcurses

### ISSUE THREAD

**Issue by jpscharf** [TobiasTheViking/sabcli#2]
OS: Mac OS X 10.8.4
sabcli version: master
ncurses version: 5.9

sabcli will show the history, but when I attempt to view the history on sabcurses I get the following:

```
29 - 93
Traceback (most recent call last):
  File "sabcurses.py", line 1459, in main
    mainloop(sabnzbd)
  File "sabcurses.py", line 1187, in mainloop
    sabnzbd.display()
  File "sabcurses.py", line 915, in display
    self.run_commands('history', None)
  File "sabcurses.py", line 865, in run_commands
    self.print_history()
  File "sabcurses.py", line 591, in print_history
    self.pad.addstr('\n')
error: addstr() returned ERR
```

**Comment by TobiasTheViking** [comment]
Confirmed.

**Comment by TobiasTheViking** [comment]
I*m not really sure how to fix this(besides for a total refactor of sabcurses, which is sorely needed).

I suggest you clear your history as a work-around.

**Comment by bru73f0rc3** [comment]
same issue. 
I actually use my history for reference, but i guess i could copy it off and start appending history into the new location...
